framework:
    messenger:
        failure_transport: failed

        transports:
            sync: 'sync://' 
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            # 👉 Envoie immédiat (mode synchrone)
            Symfony\Component\Mailer\Messenger\SendEmailMessage: sync
            # Les autres restent async si tu veux
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
