security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User  # <-- بدّل هذا إذا اسم الكلاس عندك مختلف
        property: email         # <-- بدّل إذا تستعمل username عوض email

    users_in_memory: { memory: null }  # مفيد وقت التطوير

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path: app_login       # Route name متاع صفحة login
        check_path: app_login       # نفس الشيء إذا تستعمل نفس المسار
        default_target_path: app_home # بعد login ناجح
        username_parameter: _username
        password_parameter: _password

      logout:
        path: app_logout            # لازم يكون عندك Route بهذا الاسم
        target: app_login           # بعد logout يرجّع لل login

  access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }       # يسمح لأي حد يدخل صفحة login
    - { path: ^/logout, roles: PUBLIC_ACCESS }      # نفس الشيء لل logout
    - { path: ^/daschbord, roles: ROLE_ADMIN }  
        # يحمي صفحة dashboard
